const products = [
  {
    _id: "1",
    name: "Product 1",
    image: "/images/airpods.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 1",
    category: "Category 1",
    price: 19.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 8,
  },
  {
    _id: "2",
    name: "Product 2",
    image: "/images/alexa.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 2",
    category: "Category 2",
    price: 29.99,
    countInStock: 5,
    rating: 3.8,
    numReviews: 12,
  },
  {
    _id: "3",
    name: "Product 3",
    image: "/images/camera.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 3",
    category: "Category 1",
    price: 39.99,
    countInStock: 2,
    rating: 4.2,
    numReviews: 5,
  },
  {
    _id: "4",
    name: "Product 4",
    image: "/images/mouse.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 2",
    category: "Category 3",
    price: 49.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 10,
  },
  {
    _id: "5",
    name: "Product 5",
    image: "/images/phone.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 1",
    category: "Category 2",
    price: 59.99,
    countInStock: 3,
    rating: 4.7,
    numReviews: 15,
  },
  {
    _id: "6",
    name: "Product 6",
    image: "/images/playstation.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 3",
    category: "Category 1",
    price: 69.99,
    countInStock: 0,
    rating: 4.9,
    numReviews: 20,
  },
  {
    _id: "7",
    name: "Product 7",
    image: "/images/sample.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 2",
    category: "Category 3",
    price: 79.99,
    countInStock: 4,
    rating: 3.5,
    numReviews: 6,
  },
  {
    _id: "8",
    name: "Product 8",
    image: "/images/screens.png",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 1",
    category: "Category 2",
    price: 89.99,
    countInStock: 9,
    rating: 4.6,
    numReviews: 18,
  },
];

export default products;
